server:
  port: 9090
spring:  datasource:    url: jdbc:mysql://usrmgmtdb.cku85b0ixroa.ap-south-1.rds.amazonaws.com/usermgmt
    username: admin
    password: srinivas123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:      ddl-auto: update

  mail:     host: smtp.gamil.com
    port: 587
    username: techit2050@gmail.com
    password: Adwaith@2019
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true app:
  messages:
    InvalidCred:  Invalid user Credentials
    AccLocked: Account is Locked
    LoginSuccess: Login Success
    NewEmail: New Email
    Duplicate: Duplicate
    UnLockAcc: Unlock Your Account
    RegSuccess: Registration Completed Successfully
    InvalidAcc: Invalid Account Please provide correct Email
    AccUnlocked: Account Unlocked
    PswdSent: Password sent to Email
    
    
    
    
    
    
         